version: '3.8'

services:
  database:
    image: postgres:13.0-alpine
    container_name: database
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: menshikovas/api_yamdb
    container_name: web
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - database
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/

    depends_on:
      - web

volumes:
  db_data:
  static_value:
  media_value:
